name: Build and Publish Docker Images

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
    strategy:
      matrix:
        arch: [amd64, arm64]
    outputs:
      commit_hash: ${{ steps.get_commit_hash.outputs.hash }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Get Commit Hash
        id: get_commit_hash
        run: echo "hash=$(git rev-parse --short HEAD)" >> $GITHUB_ENV && echo "::set-output name=hash::$(git rev-parse --short HEAD)"

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache-ledger-auth-${{ matrix.arch }}
          key: ${{ runner.os }}-ledger-auth-buildx-${{ matrix.arch }}-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-ledger-auth-buildx-${{ matrix.arch }}-

      - name: Build Docker image
        uses: docker/build-push-action@v3
        with:
          file: ./Dockerfile
          build-args: |
            COMMIT_HASH=${{ env.hash }}
          push: true
          platforms: linux/${{ matrix.arch }}
          cache-from: type=local,src=/tmp/.buildx-cache-ledger-auth-${{ matrix.arch }}
          cache-to: type=local,dest=/tmp/.buildx-cache-ledger-auth-${{ matrix.arch }}-new,mode=max
          tags: |
            ghcr.io/ldg-sh/ledger-auth:${{ env.hash }}-${{ matrix.arch }}

      - name: Move updated Docker cache
        run: |
          rm -rf /tmp/.buildx-cache-ledger-auth-${{ matrix.arch }}
          mv /tmp/.buildx-cache-ledger-auth-${{ matrix.arch }}-new /tmp/.buildx-cache-ledger-auth-${{ matrix.arch }}

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      packages: write

    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push multi-arch manifest
        run: |
          docker buildx imagetools create \
            -t ghcr.io/ldg-sh/ledger-auth:latest \
            ghcr.io/ldg-sh/ledger-auth:${{ needs.build.outputs.commit_hash }}-amd64 \
            ghcr.io/ldg-sh/ledger-auth:${{ needs.build.outputs.commit_hash }}-arm64
